// All Google Fonts — sorted by popularity. Used for autocomplete.
export const GOOGLE_FONTS = [
  'Roboto','Open Sans','Noto Sans','Lato','Montserrat','Poppins','Inter','Oswald',
  'Raleway','PT Sans','Merriweather','Nunito','Ubuntu','Playfair Display','Source Sans 3',
  'Libre Baskerville','PT Serif','Crimson Text','Josefin Sans','Barlow','Mulish',
  'Work Sans','Noto Serif','Rubik','Fira Sans','Cabin','Titillium Web','Quicksand',
  'Kanit','DM Sans','Karla','Exo 2','Oxygen','Heebo','Bitter','Arvo','Zilla Slab',
  'Dosis','Comfortaa','Varela Round','Manrope','Outfit','Figtree','Plus Jakarta Sans',
  'Syne','Space Grotesk','Jost','Lexend','Barlow Condensed','Barlow Semi Condensed',
  'IBM Plex Sans','IBM Plex Serif','IBM Plex Mono','DM Serif Display','DM Serif Text',
  'DM Mono','Fira Code','Inconsolata','Space Mono','Roboto Mono','Roboto Condensed',
  'Roboto Slab','Cormorant Garamond','Cormorant','EB Garamond','Libre Franklin',
  'Source Serif 4','Spectral','Volkhov','Vollkorn','Old Standard TT','Neuton',
  'Unna','Vidaloka','Lustria','Cardo','Gentium Plus','Nobile','Domine','Rokkitt',
  'Josefin Slab','BioRhyme','Cinzel','Piazzolla','Fraunces','Bodoni Moda','Rufina',
  'Vesper Libre','Besley','Ibarra Real Nova','Corben','Della Respira','Podkova',
  'Philosopher','Quattrocento','Quattrocento Sans','Coda','Neuton','Vidaloka',
  'Lobster','Pacifico','Dancing Script','Righteous','Kaushan Script','Chewy',
  'Permanent Marker','Amatic SC','Caveat','Satisfy','Cookie','Great Vibes',
  'Allura','Sacramento','Parisienne','Shadows Into Light','Indie Flower',
  'Architects Daughter','Annie Use Your Telescope','Kalam','Patrick Hand',
  'Handlee','Italianno','Alex Brush','Yellowtail','Lobster Two','Mr Dafoe',
  'Courgette','Leckerli One','Oleo Script','Diplomata SC','Euphoria Script',
  'Fredericka the Great','Monoton','Cinzel Decorative','Special Elite',
  'VT323','Press Start 2P','Bungee','Bungee Inline','Alfa Slab One','Lilita One',
  'Anton','Russo One','Orbitron','Exo','Quantico','Rajdhani','Teko','Changa',
  'Graduate','Squada One','Saira','Saira Condensed','Saira Semi Condensed',
  'Yanone Kaffeesatz','Questrial','Overpass','Maven Pro','Hind','Catamaran',
  'Asap','Asap Condensed','Encode Sans','Encode Sans Condensed','Epilogue',
  'Chivo','Assistant','Hanken Grotesk','Urbanist','Red Hat Display','Red Hat Text',
  'Public Sans','Lexend Deca','Tourney','Smooch Sans','Truculenta','League Gothic',
  'League Spartan','Sarabun','Tajawal','Cairo','Harmattan','Amiri','Scheherazade New',
  'Noto Kufi Arabic','Reem Kufi','Mada','Mirza','Markazi Text','Lemonada',
  'Mina','Fahkwang','Chakra Petch','Kanit','Sora','Bebas Neue','Pridi',
  'Krub','Charm','Charmonman','Moo Lah Lah','Prompt','Sarabun','Taviraj',
  'Thasadith','Kodchasan','Bai Jamjuree','Athiti','K2D','Mali','Mitr',
  'Niramit','Sriracha','Itim','Proza Libre','Eczar','Karma','Hind Madurai',
  'Hind Siliguri','Hind Guntur','Hind Vadodara','Mukta','Mukta Malar',
  'Mukta Mahee','Mukta Vaani','Laila','Palanquin','Palanquin Dark','Kurale',
  'Tiro Devanagari Hindi','Tiro Devanagari Sanskrit','Yatra One',
  'Recursive','Secular One','Signika','Signika Negative','Rowdies','Viga',
  'Overlock','Didact Gothic','News Cycle','Cuprum','Economica','Forum',
  'Noticia Text','Rokkitt','Ropa Sans','PT Mono','PT Sans Narrow','PT Sans Caption',
  'Noto Sans Mono','Courier Prime','Share Tech Mono','Source Code Pro',
  'Anonymous Pro','Cutive Mono','Oxygen Mono','Nova Mono','B612 Mono',
  'Azeret Mono','Martian Mono','Nanum Gothic Coding','Ubuntu Mono',
  'Jura','Josefin Sans','Numans','Bree Serif','Lora','Martel','Martel Sans',
  'Nanum Myeongjo','Nanum Gothic','Nanum Pen Script','Jua','Do Hyeon',
  'Black Han Sans','Sunflower','Gamja Flower','Gaegu','East Sea Dokdo',
  'Song Myung','Kirang Haerang','Poor Story','Hi Melody','Black And White Picture',
  'Gowun Batang','Gowun Dodum','Hahmlet','Nanum Brush Script','Single Day',
  'Cute Font','Gothic A1','Stylish','Noto Serif KR','Noto Sans KR',
  'M PLUS 1p','M PLUS Rounded 1c','Kosugi','Kosugi Maru','Sawarabi Gothic',
  'Sawarabi Mincho','Noto Serif JP','Noto Sans JP','Murecho','BIZ UDPGothic',
  'BIZ UDPMincho','BIZ UDMincho','BIZ UDGothic','Dela Gothic One',
  'Hachi Maru Pop','Klee One','Mochiy Pop One','Mochiy Pop P One',
  'Rampart One','RocknRoll One','Stick','Train One','Yomogi','Zen Antique',
  'Zen Antique Soft','Zen Kaku Gothic Antique','Zen Kaku Gothic New',
  'Zen Kurenaido','Zen Maru Gothic','Zen Old Mincho',
  'Noto Sans SC','Noto Serif SC','ZCOOL KuaiLe','ZCOOL QingKe HuangYou',
  'ZCOOL XiaoWei','Ma Shan Zheng','Long Cang','Liu Jian Mao Cao',
  'Zhi Mang Xing','Smiley Sans','Tsukimi Rounded',
  'Titillium Web','Raleway Dots','Boogaloo','Fredoka','Fredoka One',
  'Pattaya','Sriracha','Battambang','Hanuman','Bayon','Moul','Koulen',
  'Nokora','Siemreap','Dangrek','Freehand','Kantumruy Pro','Fasthand',
  'Bokor','Chenla','Content','Metal','Moul Pali','Suwannaphum',
  'Arima','Arima Madurai','Catamaran','Faustina','Numans','Balthazar',
  'Bentham','Artifika','Alike','Alike Angular','Amaranth','Amethysta',
  'Amiri Quran','Anaheim','Andada Pro','Andika','Angkor','Anta',
  'Antic','Antic Didone','Antic Slab','Antonio','Anybody','Arapey',
  'Arbutus','Arbutus Slab','Architects Daughter','Archivo','Archivo Black',
  'Archivo Narrow','Aref Ruqaa','Aref Ruqaa Ink','Armata','Arsenal',
  'Ovo','Padauk','Palanquin','Petrona','Pirata One','Poiret One',
  'Pontano Sans','Port Lligat Sans','Port Lligat Slab','Prata','Prociono',
  'Prosto One','Puritan','Purple Purse','Quando','Radley','Raleway Dots',
  'Rambla','Rammetto One','Rationale','Redressed','Reenie Beanie',
  'Revalia','Rhodium Libre','Ribeye','Ribeye Marrow','Righteous','Risque',
  'Rochester','Rock Salt','Lekton','Libre Barcode 128','Libre Barcode 128 Text',
  'Libre Barcode 39','Libre Barcode 39 Extended','Libre Barcode 39 Extended Text',
  'Libre Barcode 39 Text','Sancreek','Sansita','Sansita Swashed','Saira Stencil One',
  'Salsa','Sanchez','Scheherazade New','Scada','Sevillana','Seymour One',
  'Shanti','Shippori Mincho','Shippori Mincho B1','Short Stack','Shrikhand',
  'Simonetta','Six Caps','Skranji','Slabo 13px','Slabo 27px','Slackey',
  'Smokum','Snowburst One','Sofadi One','Sofia','Sonsie One','Souliyo',
  'Source Serif 4','Spartan','Spinnaker','Spirax','Spline Sans',
  'Spline Sans Mono','Sprite Grotesk','Stardos Stencil','Stint Ultra Condensed',
  'Stint Ultra Expanded','Stoke','Strait','Sue Ellen Francisco','Suez One',
  'Sumana','Sunflower','Suwannaphum','Syncopate','Telex','Tienne',
  'Timmana','Tinos','Titan One','Trirong','Trispace','Trocchi',
  'Trochut','Tsukimi Rounded','Tulpen One','Turret Road','Twinkle Star',
  'Ubuntu Condensed','Unkempt','Unlock','Unica One','UnifrakturCook',
  'UnifrakturMaguntia','Updock','Uchen','Ultra','Ulcinj','Vandal',
  'Vibes','Vibur','Victor Mono','Viga','Voltaire','Waiting for the Sunrise',
  'Wallpoet','Walter Turncoat','Warnes','Wellfleet','Wendy One','Wire One',
  'Wix Madefor Display','Wix Madefor Text','Xanh Mono','Yaldevi','Yantramanav',
  'Yeseva One','Yesteryear','Young Serif','Yuji Boku','Yuji Mai','Yuji Syuku',
  'Yujia Boku','Yusei Magic','Zeyada','Zen Loop','Zhuri Neue',
].sort();
